
# Site settings
title-en: Mehdi Shahamirian
title-fa: مهدی شاه امیریان
email: mehdi@shahamirian.info
description-fa: > # this means to ignore newlines until "baseurl:"
  یک توسعه دهنده سمت کاربر، عاشق واسط(رابط) کاربری و علاقه مند به تجربه کاربری. همچنین علاقه مند به ساده سازی فرایندها و بهبود کارایی.
description-en: >
  I'm a Front-End Developer, UI lover and UX enthusiast, who is interested in building, simplifying and making things work better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shahamirian.info" # the base hostname & protocol for your site
twitter_username: mshahamirian
github_username:  mshahamirian

# Build settings
markdown: kramdown
# permalink: title
#paginate: 5
#paginate_path: /page:num
sass:
    style: compressed
